### PR TITLE
Add bank.bulckcah.com

### PR DESCRIPTION
**Pull request by exu3**
I don't know if I did this right, but this PR intends to add a proxy for bank.hackclub.com https://hackclub.slack.com/archives/C026RKHLPNJ/p1633719716106900?thread_ts=1633718047.106300&cid=C026RKHLPNJ

### CODE REVIEW

**Comment by cjdenio** [comment]
Looks good to me!

**Comment by cjdenio** [comment]
https://user-images.githubusercontent.com/34525547/147318076-adbbd34c-2156-45bc-b098-520d1841897b.mov

I think a workable solution would be to point bank.bulckcah.com to Heroku.

**Comment by garyhtou** [comment]
ahh smart idea. i'll think this over (with consideration of how bank's designed) and get back to yall

**Comment by garyhtou** [comment]
I had made a minor change to Bank (https://github.com/hackclub/bank/commit/5c3727b14c536bdef1eb99f68ebb5d7152bc2a5e). There's still stuff hardcoded in the rails credentials, but let give it a shot! We can revert this PR then try adding bank.bulckcah.com to heroku

**Pull request merged**
